apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
  - pdb.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: panda-ocpp-api-config
    literals:
      - PORT="4002"
      - RABBITMQ_QUEUE="PANDA_EV_QUEUE"
      - RABBITMQ_COMMANDS_QUEUE="PANDA_EV_CSMS_COMMANDS"
      - RABBITMQ_ADMIN_COMMANDS_QUEUE="PANDA_EV_ADMIN_COMMANDS"
      - RABBITMQ_CHARGER_SYNC_QUEUE="PANDA_EV_CHARGER_SYNC"
      - SERVICE_NAME="ocpp-csms"
