apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: panda-ev-certs
  namespace: panda-ev
spec:
  domains:
    - admin-api.pandaev.cc
    - api.pandaev.cc
    - gateway-api.pandaev.cc