apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: panda-ev-dev

resources:
  # 1. Infrastructure (Global)
  - ../../infrastructure/ingress/overlays/dev
  # 2. Stateful Services
  - ../../infrastructure/stateful/redis/overlays/dev
  - ../../infrastructure/stateful/rabbitmq/overlays/dev
  # 3. Application Services
  - ../../services/panda-ev-client-mobile/overlays/dev
  - ../../services/panda-ev-csms-system-admin/overlays/dev
  - ../../services/panda-ev-gateway-services/overlays/dev
  - ../../services/panda-ev-notification/overlays/dev
  - ../../services/panda-ocpp-api/overlays/dev

generatorOptions:
  disableNameSuffixHash: true
