apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: panda-mobile-api-backendconfig
spec:
  timeoutSec: 3600
  connectionDraining:
    drainingTimeoutSec: 60
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    port: 4001
    requestPath: /health
