apiVersion: v1
kind: Service
metadata:
  name: panda-mobile-api-service
  labels:
    app: panda-mobile-api
  annotations:
    cloud.google.com/backend-config: '{"default": "panda-mobile-api-backendconfig"}'
spec:
  type: NodePort
  selector:
    app: panda-mobile-api
  ports:
    - name: http
      port: 80
      targetPort: 4001
